# INPUT_DATA: str = """.......S.......
# ...............
# .......^.......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ..............."""
with open("2025/day_07/d7_input.txt") as f: INPUT_DATA: str = f.read()

lines: list[str] = INPUT_DATA.split('\n') 
timelines: list[int] = [0] * len(lines[0])
timelines[lines[0].find('S')] = 1

for line in lines[2::2]:
    for idx, c in enumerate(line[1:-1]):
        if c == '^' and timelines[idx+1]:
            timelines[idx] += timelines[idx+1]
            timelines[idx+2] += timelines[idx+1]
            timelines[idx+1] = 0
           
print(f"\nAmount of timelines: {sum(timelines)}")

# personal solution: 5921061943075