from typing import LiteralString

INPUT_DATA: LiteralString = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

lines: list[LiteralString] = INPUT_DATA.split('\n')
beams: list[bool] = [False] * len(lines[0])
beams[lines[0].find('S')] = True
splitter_count: int = 0

for line in lines[2::2]:
    for idx, c in enumerate(line[1:-1]):
        if c == '^' and beams[idx+1]:
            beams[idx+1] = False
            splitter_count += 1
            beams[idx] = True
            beams[idx+2] = True
            
print(f"\nAmount of splits: {splitter_count}")

# personal solution: 1566