from typing import LiteralString

INPUT_DATA: LiteralString = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

lines: list[LiteralString] = INPUT_DATA.split('\n') 
timelines: list[int] = [0] * len(lines[0])
timelines[lines[0].find('S')] = 1

for line in lines[2::2]:
    for idx, c in enumerate(line[1:-1]):
        if c == '^' and timelines[idx+1]:
            timelines[idx] += timelines[idx+1]
            timelines[idx+2] += timelines[idx+1]
            timelines[idx+1] = 0
           
print(f"\nAmount of timelines: {sum(timelines)}")

# personal solution: 5921061943075